---

- hosts: all
  become: true
  pre_tasks:


  - name: install updates (centos)
    tags: always
    yum:
      update_only: yes
      update_cache: yes

    when: ansible_distribution == "CentOS"

  - name: install update (ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:
  - name: create milad user
    tags: always
    user:
      name: milad
      groups: root

  - name: create ssh key for user milad
    tags: always
    authorized_key:
      user: milad
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEfjPaOBJ1LxdRTdu+YARS/PJBtfcf/c7aqdP7r50oGO root@ansible-node"

  - name: add sudoer file for milad
    tags: always
    copy:
      src: sudoer_milad
      dest: /etc/sudoers.d/milad
      owner: root
      group: root
      mode: 0440


