---

- hosts: all
  become: true
  tasks:

  - name: update index repository
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache package2
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"    

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update index repository
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache package2
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"    

  - name: add php support for apache
    yum:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"
