---

- hosts: all
  become: true
  pre_tasks:


  - name: install updates (centos)
    tags: always
    yum:
      update_only: yes
      update_cache: yes

    when: ansible_distribution == "CentOS"

  - name: install update (ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstation
  become: true
  tasks:

  - name: unzip
    package:
      name: unzip
      state: latest

  - name: install terraform 
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.4.0-rc1/terraform_1.4.0-rc1_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:


  - name: install apache2 and php for ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install httpd and php
    tags: apache,httpd,centos
    yum:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb on centos
    tags: db,mariadb,centos
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  -  name: install mariadb on ubuntu
     tags: db,mariadb,ubuntu
     apt:
       name: mariadb-server
       state: latest
     when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba
    tags: samba
    package:
      name: samba
      state: latest

